import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { ROOT, run } from './common.mjs';
import { pushOverleaf, publishRequestedOverleaf } from './overleaf-cv.mjs';

test('optional publication skips unrequested and failed reviews and reports push failures', async () => {
  let calls = 0;
  const publish = async () => { calls++; return { pushed: true }; };
  const opts = { requested: false, source: 'overleaf', job: {}, pack: { dir: 'synthetic' } };
  assert.equal((await publishRequestedOverleaf(opts, publish)).pushed, false);
  assert.equal((await publishRequestedOverleaf({ ...opts, requested: true, pack: { ...opts.pack, needsReview: true } }, publish)).pushed, false);
  await assert.rejects(publishRequestedOverleaf({ ...opts, requested: true, source: 'local' }, publish), /Overleaf CV mode/);
  assert.equal(calls, 0);
  assert.equal((await publishRequestedOverleaf({ ...opts, requested: true }, publish)).pushed, true);
  assert.equal(calls, 1);
  const failed = await publishRequestedOverleaf({ ...opts, requested: true }, async () => { throw new Error('Remote changed'); });
  assert.equal(failed.failed, true);
  assert.equal(failed.pushed, false);
  assert.equal(opts.pack.dir, 'synthetic');
  const controller = new AbortController(); controller.abort();
  await assert.rejects(publishRequestedOverleaf({ ...opts, requested: true, signal: controller.signal }, publish), /abort/i);
  assert.equal(calls, 1);
});

test('push commits only CV sources and rejects a concurrent remote update', async t => {
  const parent = join(ROOT, '.workspace', 'tests');
  await mkdir(parent, { recursive: true });
  const root = await mkdtemp(join(parent, 'overleaf-publish-'));
  t.after(async () => { assert.equal(dirname(root), parent); await rm(root, { recursive: true, force: true }); });
  const remote = join(root, 'remote.git');
  const seed = join(root, 'seed');
  const dir = join(root, 'draft');
  const git = (where, ...args) => run('git', ['-C', where, ...args]);
  await run('git', ['init', '--bare', '--quiet', remote]);
  await run('git', ['clone', remote, seed]);
  for (const name of ['main.tex', 'ats.tex', 'notes.md']) await writeFile(join(seed, name), 'Master');
  await git(seed, 'add', '.');
  await git(seed, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'Master');
  await git(seed, 'push');
  await run('git', ['clone', remote, dir]);
  await git(dir, 'config', 'user.name', 'Test');
  await git(dir, 'config', 'user.email', 'test@example.com');
  for (const name of ['main.tex', 'ats.tex', 'notes.md', 'build.pdf']) await writeFile(join(dir, name), 'Draft');
  await git(dir, 'add', 'notes.md');
  assert.equal((await pushOverleaf('Reviewed CV', { dir })).pushed, true);
  assert.equal((await git(remote, 'show', 'HEAD:main.tex')).stdout.trim(), 'Draft');
  assert.equal((await git(remote, 'show', 'HEAD:notes.md')).stdout.trim(), 'Master');
  assert.equal((await git(remote, 'ls-tree', '--name-only', 'HEAD')).stdout.includes('build.pdf'), false);
  assert.equal((await pushOverleaf('Same CV', { dir })).pushed, false);
  await git(seed, 'pull', '--ff-only');
  await writeFile(join(seed, 'main.tex'), 'New online master');
  await git(seed, 'add', 'main.tex');
  await git(seed, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'Online edit');
  await git(seed, 'push');
  await writeFile(join(dir, 'main.tex'), 'Another CV');
  await assert.rejects(pushOverleaf('Concurrent CV', { dir }));
  assert.equal((await git(remote, 'show', 'HEAD:main.tex')).stdout.trim(), 'New online master');
  assert.equal(await readFile(join(dir, 'main.tex'), 'utf8'), 'Another CV');
});
