import test from 'node:test';
import assert from 'node:assert/strict';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { prepFingerprint, loadPrepInputs } from './prep-state.mjs';
import { ROOT } from './common.mjs';

test('manual application lifecycle and submitted files through the real HTTP routes', { timeout: 30000 }, async (t) => {
  const parent = resolve(ROOT, '.workspace/tests');
  await mkdir(parent, { recursive: true });
  const root = await mkdtemp(join(parent, 'tracker-http-'));
  assert.ok(resolve(root).startsWith(parent + sep));
  let child;
  t.after(async () => {
    if (child && child.exitCode == null && child.signalCode == null) { const exit = once(child, 'exit'); child.kill(); await exit; }
    await rm(root, { recursive: true, force: true });
  });
  for (const dir of ['scripts/lib', 'web', 'markets']) await cp(join(ROOT, dir), join(root, dir), { recursive: true });
  await writeFile(join(root, 'package.json'), '{"type":"module"}');
  await mkdir(join(root, '.workspace'), { recursive: true });
  await writeFile(join(root, 'profile.json'), JSON.stringify({ name: 'Test', search: { titles: ['Developer'], includeTitlePatterns: ['Developer'] } }));
  await writeFile(join(root, 'search-profile.json'), JSON.stringify({ market: 'DE', filters: { maxAgeDays: 30 }, cv: { source: 'local', agentProvider: 'cursor', agentModel: 'test-model' } }));
  const jobs = Array.from({ length: 63 }, (_, i) => ({ id: `test:${i}`, company: `Company ${i}`, title: 'Developer', location: 'Berlin, Germany', description: 'Software developer role.', postedAt: new Date().toISOString(), url: `https://example.com/${i}` }));
  await writeFile(join(root, '.workspace/jobs.json'), JSON.stringify({ jobs }));
  await writeFile(join(root, '.workspace/digest.json'), JSON.stringify({ newIds: jobs.map(job => job.id) }));
  const profile = JSON.parse(await readFile(join(root, 'profile.json'), 'utf8'));
  const settings = { source: 'local', agentProvider: 'cursor', agentModel: 'test-model' };
  const inputs = await loadPrepInputs(settings, root);
  for (const job of jobs.slice(0, 16)) {
    const dir = join(root, '.workspace/prep', job.id.replace(':', '_'));
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, 'cv.html'), '<p>Test CV</p>');
    await writeFile(join(dir, 'generation.json'), JSON.stringify({ cv: { fingerprint: prepFingerprint({ job, profile, settings, inputs, scope: 'cv' }) } }));
  }
  const server = join(root, 'web/server.mjs');
  await writeFile(server, (await readFile(server, 'utf8')).replace('server.listen(PORT, () => {', 'server.listen(PORT, () => { process.send({ port: server.address().port });'));
  child = spawn(process.execPath, [server], { cwd: root, windowsHide: true, env: { ...process.env, PORT: '0', NO_OPEN: '1', GOOGLE_SHEETS_SPREADSHEET_ID: '', APIFY_TOKEN: '', OVERLEAF_GIT_TOKEN: '', OVERLEAF_PROJECT_ID: '' }, stdio: ['ignore', 'pipe', 'pipe', 'ipc'] });
  let logs = '';
  child.stderr.on('data', (data) => { logs += data; });
  child.stdout.resume();
  const [{ port }] = await Promise.race([once(child, 'message'), once(child, 'exit').then(() => { throw new Error(logs); })]);
  const base = `http://127.0.0.1:${port}`;
  const request = async (path, body, method = 'POST') => {
    const response = await fetch(base + path, { method, headers: { 'content-type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
    return { status: response.status, data: await response.json() };
  };
  const light = await request('/api/status?light=1', null, 'GET');
  assert.equal(light.status, 200);
  assert.equal(light.data.readyCount, null);
  assert.deepEqual(light.data.agentProviders, []);
  const digestOne = await request('/api/digest?page=1&pageSize=20', null, 'GET');
  const digestTwo = await request('/api/digest?page=2&pageSize=20', null, 'GET');
  assert.equal(digestOne.data.pagination.total, 63);
  assert.equal(digestOne.data.newJobs.length, 20);
  assert.equal(digestTwo.data.pagination.page, 2);
  assert.equal(new Set([...digestOne.data.newJobs, ...digestTwo.data.newJobs].map(job => job.id)).size, 40);
  const selection = await request('/api/digest?selection=1', null, 'GET');
  assert.equal(selection.data.candidates.length, 63);
  assert.equal(selection.data.candidates[0].description, undefined);
  const results = await request('/api/jobs?page=99&pageSize=20', null, 'GET');
  assert.equal(results.data.pagination.page, 4);
  assert.equal(results.data.jobs.length, 3);
  assert.equal(results.data.companies, undefined);
  const ready = await request('/api/ready', null, 'GET');
  assert.equal(ready.data.pagination.total, 16);
  assert.equal(ready.data.jobs.length, 10);
  const readyTwo = await request('/api/ready?page=2', null, 'GET');
  assert.equal(readyTwo.data.jobs.length, 6);
  assert.equal(new Set([...ready.data.jobs, ...readyTwo.data.jobs].map(job => job.id)).size, 16);
  const added = await request('/api/tracker/application', { company: 'Manual Co', title: 'Engineer', decision: 'applied', appliedDate: '2026-08-01', contactName: 'Taylor', url: 'https://example.com/job' });
  assert.equal(added.status, 201);
  const id = added.data.entry.id;
  assert.ok(id.startsWith('manual:application:'));
  assert.equal((await request('/api/tracker/application', { id, decision: 'offer' }, 'PATCH')).status, 200);
  const payload = { id, name: 'CV.txt', kind: 'cv', data: Buffer.from('Submitted CV bytes').toString('base64') };
  const attached = await request('/api/tracker/attachments', payload);
  assert.equal(attached.status, 201);
  const attachment = attached.data.attachment.id;
  const downloaded = await fetch(`${base}/api/tracker/attachments?id=${encodeURIComponent(id)}&attachment=${attachment}`);
  assert.equal(await downloaded.text(), 'Submitted CV bytes');
  assert.match(downloaded.headers.get('content-disposition'), /^attachment;/);
  assert.equal((await fetch(`${base}/api/tracker/attachments?id=wrong&attachment=${attachment}`)).status, 404);
  await request('/api/decisions', { id, decision: 'accepted' });
  const tracker = await request('/api/tracker', null, 'GET');
  assert.equal(tracker.data.counts.accepted, 1);
  const entry = tracker.data.items[0];
  assert.equal(entry.appliedDate, '2026-08-01');
  assert.equal(entry.contactName, 'Taylor');
  assert.equal(entry.attachments.length, 1);
  assert.deepEqual(entry.statusHistory.map((h) => h.to), ['applied', 'offer', 'accepted']);
  assert.equal((await request('/api/tracker/application', { company: '', title: 'Dev' })).status, 400);
  assert.equal((await request('/api/tracker/application', { id, url: 'javascript:alert(1)' }, 'PATCH')).status, 400);
});
